import Header from "@/components/Header"
import "./globals.css"
import { Poppins } from "next/font/google"

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata = {
	title: "Youtube Advance",
	description: "Generated by create next app",
	icons: {
		icon: "https://i.ibb.co/s9Qys2j/logo.png",
	},
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
			</body>
		</html>
	)
}
